grumphp:
    process_timeout: 3600
    parallel:
        enabled: true
        max_workers: 32
    fixer:
        enabled: false
        fix_by_default: false
    stop_on_failure: false
    ignore_unstaged_changes: true
    hide_circumvention_tip: false

    testsuites:
        php:
            tasks:
                - phpcs
                - phplint
                - jsonlint
                - yamllint
        theme:
            tasks:
                - phpcs
                - phplint
                - jsonlint
                - yamllint
                - eslint
                - twigcs
        js:
            tasks:
                - eslint
                - jsonlint
        static:
            tasks:
                - securitychecker_symfony
                # - phpcpd
                - phpstan


    extensions:
        - IsedIsde\ConventionsDrupal\GrumphpTasksExtension

    # Tasks.
    tasks:

        # Composer checks
        composer: ~

        # Composer Normalize
        composer_normalize: ~

        # PHP Code Sniffer.
        phpcs:
            report: '%tasks.phpcs.report%'
            sniffs: '%tasks.phpcs.sniffs%'
            exclude: '%tasks.phpcs.exclude%'
            ignore_patterns: '%tasks.phpcs.ignore_patterns%'
            standard: '%tasks.phpcs.standard%'
            triggered_by: '%tasks.phpcs.triggered_by%'
            whitelist_patterns: '%tasks.phpcs.whitelist_patterns%'
            warning_severity: '%tasks.phpcs.warning_severity%'
            metadata:
                priority: '%tasks.phpcs.metadata.priority%'

        # PHP Lint
        phplint:
            ignore_patterns: '%tasks.phplint.ignore_patterns%'
            triggered_by: '%tasks.phplint.triggered_by%'

        # JSON Lint
        jsonlint:
            ignore_patterns: '%tasks.jsonlint.ignore_patterns%'
            detect_key_conflicts: '%tasks.jsonlint.detect_key_conflicts%'

        # YAML Lint
        yamllint:
            whitelist_patterns: []
            ignore_patterns: []
            object_support: true
            exception_on_invalid_type: true
            parse_constant: true
            parse_custom_tags: true

        # Javascript Lint
        eslint:
            bin: '%tasks.eslint.bin%'
            triggered_by: '%tasks.eslint.triggered_by%'
            whitelist_patterns: '%tasks.eslint.whitelist_patterns%'
            config: '%tasks.eslint.config%'
                    
        # Twig CS
        twigcs:
            path: '%tasks.twigcs.path%'
            ruleset: '%tasks.twigcs.ruleset%'
            severity: '%tasks.twigcs.severity%'
            triggered_by: '%tasks.twigcs.triggered_by%'
            exclude: '%tasks.twigcs.exclude%'


        # GIT pre-commit message checker
        git_commit_message:
            allow_empty_message: false
            enforce_capitalized_subject: true
            enforce_no_subject_punctuations: false
            enforce_no_subject_trailing_period: false
            enforce_single_lined_subject: true
            type_scope_conventions: []
            max_body_width: 72
            max_subject_width: 80
            matchers: '%tasks.git_commit_message.matchers%'  
            case_insensitive: true
            multiline: true
            additional_modifiers: ''

parameters:
    tasks.phplint.ignore_patterns:
        - tests/
    tasks.phplint.triggered_by:
        - 'php'
        - 'profile'
        - 'install'
        - 'module'
        - 'theme'
        - 'inc'

    # PHP Code Sniffer parameters.
    tasks.phpcs.report: full
    tasks.phpcs.sniffs: []
    tasks.phpcs.exclude: []
    tasks.phpcs.ignore_patterns:
        - vendor/
        - node_modules/
        - tests/fixtures/
        - libraries/
        - spec
    tasks.phpcs.triggered_by:
        - php
        - profile
        - install
        - theme
        - module
        - inc
    tasks.phpcs.whitelist_patterns:
        - /(.*)/
        - /^html\/modules\/(.*)/
    tasks.phpcs.standard: 
        - Drupal
        - DrupalPractice
    tasks.phpcs.warning_severity: ~
    tasks.phpcs.metadata.priority: 1000

    # Twigcs
    tasks.twigcs.triggered_by: ['twig']
    tasks.twigcs.ruleset: 'FriendsOfTwig\Twigcs\Ruleset\Official'
    tasks.twigcs.path: 'html/profiles'
    tasks.twigcs.severity: 'warning'
    tasks.twigcs.exclude:
        - html/core
        - html/modules
        - html/themes
        - html/sites
        - vendor
        - config

    # ESLinter
    tasks.eslint.bin: node_modules/.bin/eslint
    tasks.eslint.triggered_by:
        - js
        - jsx
        - ts
        - tsx
        - vue    
    tasks.eslint.whitelist_patterns:
        - /^html\/modules\/(.*)/
    tasks.eslint.config: html/.eslintrc.json

    tasks.jsonlint.ignore_patterns:
        - tests/
        - config/
        - composer.json
        - package.json
    tasks.jsonlint.detect_key_conflicts: true

    tasks.git_commit_message.max_body_width: 0
    tasks.git_commit_message.max_subject_width: 0
