parameters:
    # PHP Code Sniffer parameters.
    tasks.phpcs.exclude: []
    tasks.phpcs.ignore_patterns:
        - vendor/
        - node_modules/
        - tests/fixtures/
        - libraries/
        - spec
    tasks.phpcs.triggered_by:
        - inc
        - install
        - module
        - php
        - profile
        - theme
    tasks.phpcs.whitelist_patterns: []
    tasks.phpcs.standard: 
        - vendor/drupal/coder/coder_sniffer/Drupal
        - vendor/drupal/coder/coder_sniffer/DrupalPractice
    tasks.phpcs.warning_severity: ~

grumphp:
    process_timeout: 3600
    parallel:
        enabled: false
        max_workers: 32
    fixer:
        enabled: true
        fix_by_default: true

    extensions:
        - Boehringer\DrupalConventions\GrumphpTasksExtension

    # Tasks.
    tasks:
        # Composer checks
        composer: ~

        # Composer Normalize
        composer_normalize: ~

        # YAML Lint
        yamllint:
            whitelist_patterns: []
            ignore_patterns: []
            object_support: true
            exception_on_invalid_type: true
            parse_constant: true
            parse_custom_tags: true

        # JSON Lint
        jsonlint:
            ignore_patterns: []
            detect_key_conflicts: true

        # PHP Lint
        phplint:
            triggered_by:
                - 'php'
                - 'profile'
                - 'install'
                - 'module'
                - 'theme'
                - 'inc'

        # Twig CS
        twigcs:
            path: '%tasks.twigcs.path%'
            ruleset: '%tasks.twigcs.ruleset%'
            severity: '%tasks.twigcs.severity%'
            triggered_by: '%tasks.twigcs.triggered_by%'

        # PHP Code Sniffer.
        phpcs:
            exclude: '%tasks.phpcs.exclude%'
            ignore_patterns: '%tasks.phpcs.ignore_patterns%'
            standard: '%tasks.phpcs.standard%'
            triggered_by: '%tasks.phpcs.triggered_by%'
            whitelist_patterns: '%tasks.phpcs.whitelist_patterns%'
            warning_severity: '%tasks.phpcs.warning_severity%'
            metadata:
                priority: 3000
